name: Sync Static Resources

on:
  push:
    branches:
      - main  # 修改为您的默认分支名称，如果不是 main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout static resources repository
      uses: actions/checkout@v2
      with:
        repository: TRoYals/notes
        path: static_resources

    - name: Checkout website repository
      uses: actions/checkout@v2
      with:
        repository: TRoYals/Naglfar28
        path: website
        token: ${{ secrets.GH_PAT}}

    - name: Install Python
      run: sudo apt-get install python3

    - name: Install rsync
      run: sudo apt-get install rsync

    - name: Process static resource files
      run: |
        python3 -c '
        import os
        import re
        def process_file(file_path):
            with open(file_path, "r") as f:
                content = f.read()
            ad_pattern = re.compile(r"```ad-(\w+)\n([\s\S]*?)\n```")
            content = ad_pattern.sub(r"::: \\1\n\\2\n:::", content)
            with open(file_path, "w") as f:
                f.write(content)
        for root, dirs, files in os.walk("static_resources"):
            for file in files:
                if file.endswith(".md"):
                    process_file(os.path.join(root, file))
        '


    - name: Copy all contents from static resources to website repository (excluding .git folder)
      run: |
        rsync -av --exclude='.git' static_resources/ website/docs/
        cd website
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add docs/
        git commit -m "Auto sync all static resources (excluding .git folder)" || true
        git push
