name: Sync Static Resources

on:
  push:
    branches:
      - main  # 修改为您的默认分支名称，如果不是 main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout static resources repository
      uses: actions/checkout@v2
      with:
        repository: TRoYals/notes
        path: static_resources

    - name: Checkout website repository
      uses: actions/checkout@v2
      with:
        repository: TRoYals/Naglfar28
        path: website
        token: ${{ secrets.GH_PAT}}
    
    - name: Install rsync
      run: sudo apt-get install rsync
      
  
    
    - name: Copy all contents from static resources to website repository (excluding .git folder)
      run: |
        rsync -av --exclude='.git' static_resources/ website/docs/
        cd website
        
    - name: Replace ad-XXX  
      run: |
        sed -i "/^\\\`ad-\(.*\)\`$/,/^\`\`\`$/ { s/^\\\`ad-\(.*\)\`$/::: \1/; }" *.md
        sed -i "/^\\\`\`\`$/,/^\`\`\`$/ { /^\`\`\`$/ !{ p; d; }; s/^/::: /; s/\n/\\n/g; }" *.md
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add docs/
        git commit -m "Auto sync all static resources (excluding .git folder)" || true
        git push
